branches:
  only:
    - master
    - travis

git:
    depth: 1
    submodules: false

language: cpp

matrix:
   include:
     - name: "linux-gcc"
       os: linux
       dist: xenial
       compiler: gcc

     - name: "linux-clang"
       os: linux
       dist: xenial
       compiler: clang

     - name: "osx"
       os: osx

sudo: required

addons:
  apt:
    update: true
    packages:
      - libboost-all-dev

  homebrew:
    update: true
    packages:
      - boost
      - boost-python
   
cache:
  directories:
    - $HOME/_cache

install: 
  - mkdir -p $HOME/_cache
  # build z3 if not cached
  - export Z3_CACHED="$(find $HOME/_cache/ -name z3 | grep -c "z3")"
  - cd $HOME/_cache
  - if [[ "$Z3_CACHED" == "0" ]] ; then git clone https://github.com/Z3Prover/z3.git ; fi
  - cd z3
  - if [[ "$Z3_CACHED" == "0" ]] ; then git checkout tags/z3-4.8.4 -b v484 ; fi
  - if [[ "$Z3_CACHED" == "0" ]] ; then python scripts/mk_make.py ; fi
  - if [[ "$Z3_CACHED" == "0" && "$TRAVIS_COMPILER" == "clang" ]] ; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi
  - if [[ "$Z3_CACHED" == "0" && "$TRAVIS_COMPILER" == "clang" ]] ; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
  - cd build
  - if [[ "$Z3_CACHED" == "0" ]] ; then make -j$(nproc) ; fi
  - sudo make install
  - which z3
  - z3 --version

script:
  - cd $TRAVIS_BUILD_DIR/
  - mkdir -p build && cd build
  - cmake .. 
  - make -j$(nproc)
  - sudo make install

after_success:
  - cd $TRAVIS_BUILD_DIR/example/simple
  - mkdir -p build && cd build
  - cmake ..
  - make

notifications:
    email: false

