branches:
  only:
    - master
    - travis
    - coverage

git:
  depth: 1
    submodules: false

language: cpp

matrix:
  include:
    - name: "linux-gcc"
      os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - gem install coveralls-lcov
      before_script:
        - source $TRAVIS_BUILD_DIR/scripts/travis/clean-coverage.sh $TRAVIS_BUILD_DIR/build
      after_success:
        - source $TRAVIS_BUILD_DIR/scripts/travis/submit-coverage.sh $TRAVIS_BUILD_DIR/build

     - name: "linux-clang"
       os: linux
       dist: xenial
       compiler: clang
       before_install:
         - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

     - name: "osx"
       os: osx

sudo: required

addons:
  apt:
    update: true
    packages:
      - libboost-all-dev
      - z3
      - libz3-dev

  homebrew:
    update: true
    packages:
      - boost
      - boost-python
      - z3
   
script:
  - cd $TRAVIS_BUILD_DIR/
  - bjam -j$(nproc)

notifications:
    email: false

